config/routes.rb
BarriaultPhotography::Application.routes.draw do
  
  resources :photos

  resources :posts

  devise_for :users

  match "photography" => redirect("http://photography.barriault.net")
  match 'blog' => 'blog#index'
  match 'programming' => 'programming#index'
  match 'contact' => 'contact#index'
  match 'about' => 'about#index'
  match 'welcome' => 'welcome#index'

  root :to => 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :published_at
  
  validates_presence_of :title
  validates_presence_of :content
  
  scope :published, lambda { 
    where("posts.published_at IS NOT NULL AND posts.published_at <= ?", Time.zone.now).order('published_at DESC')
  }  
  
  def published_date
    published_at.strftime("%m/%d/%Y")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable, :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.published

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/programming_controller.rb
class ProgrammingController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require 'smile'
  
  def index
    
    # my_nick = ENV['SMUGMUG_NICKNAME']
    # my_pass = ENV['SMUGMUG_PASSWORD']
    # smug = Smile.auth( my_nick, my_pass )
    # album = Smile::Album.find(:album_id => "21511473", :album_key => "L25jTF")
    # @photos = album.photos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    rnder = HtmlWithPrettyPrint.new(:hard_wrap => true)
    mkdwn = Redcarpet::Markdown.new(rnder, :no_intra_emphasis => true, :fenced_code_blocks => true, :space_after_headers => true)
    mkdwn.render(text).html_safe
  end
end

app/views/about/index.html.erb
<div class="hero-unit">
	<h2>Bio</h2>

	<p>I am your typical techno-geek. I absolutely love computers, programming, and photography. I received my first computer, a Commodore Vic 20, as a birthday present way back in 1981 and was hooked. Around the same time I became interested in photography when a friend's dad introduced me to his darkroom and a spare camera. By the time I graduated high school in 1983 I had already won several photography awards and had a program published in Compute magazine. In 2005 I purchased my first digital camera, a Nikon D200, and was able to combine my two passions. Today I spend my time writing enterprise class software and data driven web applications for whoever will let me, and taking photographs at every available opportunity. If you happen to have a programming or photography problem that needs to be solved, don't hesitate to <%= link_to "contact me", contact_path %>.</p>
		
	<p>You can follow me on
		<%= link_to "Facebook", "http://www.facebook.com/profile.php?id=100000080021994", :target => "_blank" %>,
		<%= link_to "Twitter", "https://twitter.com/JeffBarriault", :target => "_blank" %>, 
		and <%= link_to "LinkedIn", "http://www.linkedin.com/pub/jeff-barriault/46/7/97", :target => "_blank" %>.</p>

		<h2>Website</h2>

		<p>This website was built using <%= link_to "Ruby on Rails", "http://rubyonrails.org/", :target => "_blank" %> and is hosted on <%= link_to "Heroku", "http://www.heroku.com/", :target => "_blank" %>. This source code for this web site is available in on <%= link_to "GitHub", "https://github.com/barriault/BarriaultPhotography" %>. It is intended to be used as an example Rails app, so feel free to copy bits of it for your own project. If you would like to use it as a starting point for your own site please <%= link_to "contact me", contact_path %>.</p>
		
</div>

app/views/contact/index.html.erb
<div class="row">
	
	<div class="span2">
		<address>
			<strong><i class="icon-envelope"></i> <%= mail_to "jeff@barriault.net", "Jeff Barriault", :encode => "javascript" %></strong><br>
			<i class="icon-home"></i> Bayou Vista, TX<br>
			<i class="icon-signal"></i> (281) 797-7667
		</address>
	</div>
	
	<div class="span1">
		<%= link_to image_tag("facebook_64.png", :class => "thumbnail"), "http://www.facebook.com/100000080021994", :target => "_blank" %>
	</div>
	
	<div class="span1">
		Jeff's Facebook Profile
	</div>
	
	<div class="span1">
		<%= link_to image_tag("facebook_64.png", :class => "thumbnail"), "https://www.facebook.com/JeffsAquaponics", :target => "_blank" %>
	</div>
	
	<div class="span1">
		Jeff's Aquaponics Page
	</div>
	
	<div class="span1">
		<%= link_to image_tag("facebook_64.png", :class => "thumbnail"), "http://www.facebook.com/pages/Barriault-Photography/319732201403106", :target => "_blank" %>
	</div>
	
	<div class="span1">
		Barriault Photography Page
	</div>
	
	<div class="span1">
		<%= link_to image_tag("linkedin_64.png", :class => "thumbnail"), "http://www.linkedin.com/pub/jeff-barriault/46/7/97", :target => "_blank" %>
	</div>
	
	<div class="span1">
		Jeff's LinkedIn Profile
	</div>
	
	<div class="span1">
		<%= link_to image_tag("github_64.png", :class => "thumbnail"), "https://github.com/barriault", :target => "_blank" %>
	</div>
	
	<div class="span1">
		Jeff's GitHub Profile
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jeff Barriault</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-10990914-4']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
</head>
<body onload="prettyPrint()">
	<%= render 'shared/navigation' %>

	<div class="container">
		<% if flash[:alert] -%>
		  <div class='alert alert-error'><%= h flash[:alert] %></div>
		<% end -%>
		<% if flash[:notice] -%>
		  <div class='alert alert-success'><%= h flash[:notice] %></div>
		<% end -%>    

		<%= yield %>
		
		<%= render 'shared/footer' %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %><br />
  <%= f.text_field :title %>

  <%= f.label :content %><br />
  <%= f.text_area :content %>

  <%= f.label :published_at %><br />
  <%= f.datetime_select :published_at %>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
	
	<div class="span9">
		<% if user_signed_in? -%>
		<%= link_to 'New Post', new_post_path, :class => 'btn btn-primary' %><hr />
		<% end -%>

		<% @posts.each do |post| %>
		  <h2>
		    <%= link_to post.title, post %>
				<% if user_signed_in? -%>
		    <%= link_to 'Edit', edit_post_path(post), :class => 'btn' %>
		    <%= link_to 'Destroy', post, :class => 'btn btn-danger', confirm: 'Are you sure?', method: :delete %>
				<% end -%>
			</h2>
		  <div><%= markdown(post.content) %></div>
		  <div class="alert alert-info"><i class="icon-calendar"></i> <%= post.published_date %></div>
		<% end %>
	</div>
	
	<div class="span3">
		<div>
			<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="220" height="220"><param name="movie" value="http://cdn.smugmug.com/swfs/badge/flashbadge.swf?useLargeImages=true&nickName=barriault&feedType=popularNickname&BadgeHost=cdn.smugmug.com&albumID=21511473&albumKey=L25jTF&width=220&height=220&gridSpacing=1&gridColumns=4&gridRows=3&background=%23000000&preloaderColor=&preloaderGlow=&gridDelay=2&slideshowDelay=4&order=norandom&forceSize=&showCaptions=false&introMode=fadein&aboutlink=&sharelink=&albums=" /><param name="wmode" value="transparent" /><param name="allowScriptAccess" value="always" /><embed src="http://cdn.smugmug.com/swfs/badge/flashbadge.swf?useLargeImages=true&nickName=barriault&feedType=popularNickname&BadgeHost=cdn.smugmug.com&albumID=21511473&albumKey=L25jTF&width=220&height=220&gridSpacing=1&gridColumns=4&gridRows=3&background=%23000000&preloaderColor=&preloaderGlow=&gridDelay=2&slideshowDelay=4&order=norandom&forceSize=&showCaptions=false&introMode=fadein&aboutlink=&sharelink=&albums=" width="220" height="220"  wmode="transparent"  allowScriptAccess="always" ></embed></object>
		</div>
		
		<ul class="thumbnails">
	    <li class="span3">
				<a href="http://www.adorama.com/?kbid=67100" class="thumbnail">
					<img src="http://www.adorama.com/artworks2/banners/affil/adorama_banner_200px_200px.jpg" border=0>
				</a>
	    </a>
	    </li>
    </ul>

	</div>
	
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<%= markdown(@post.content) %>

<div class="alert alert-info"><i class="icon-calendar"></i> <%= @post.published_date %></div>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/programming/index.html.erb
<div class="row">
	
	<div class="span6">
		<h2>Specialties</h2>

		<p>Writing stable, enterprise class, bug free software and data driven web applications using Ruby on Rails, .NET, Java, and various open source libraries. </p>
	</div>
	
	<div class="span6">
		<h2>More Info</h2>

		<p>Please <%= link_to "contact me", contact_path %> with any questions. For a complete list of my work experience and references, please see my <%= link_to "LinkedIn", "http://www.linkedin.com/pub/jeff-barriault/46/7/97", :target => "_blank" %> profile. You can also view some of my projects/source code on <%= link_to "GitHub", "https://github.com/barriault", :target => "_blank" %>.</p>
	</div>
		
</div>

<div class="hero-unit">
<pre class="prettyprint linenums">
<code class="language-rb">class JeffBarriault &lt; ProgrammerAnalyst
  acts_as_consultant { :experience => "Nearly 30 years!" }

  def methodologies
    [ "OOP", "DDD", "TDD", "Design Patterns", "WCF", "SOAP", "REST", "AJAX" ]
  end

  def operating_systems
    [ "Apple OS X", "Microsoft Windows", "Linux" ]
  end

  def programming_languages
    [ "Ruby", "C#.NET", "Java", "JavaScript" ]
  end

  def development_environments
    [ "TextMate". "Xcode", "Visual Studio", "Eclipse" ]
  end

  def web_frameworks_and_libraries
    [ "Ruby on Rails", "jQuery", "ASP.NET MVC", "S#arp Architecture", "Hibernate/NHibernate" ]
  end

  def databases
    [ "Oracle", "Microsoft SQL Server", "PostgreSQL", "MySQL", "SQLite", "MS Access" ]
  end

  def source_control
    [ "Git", "SVN", "Microsoft Team Foundation" ]
  end
end</code></pre>
</div>

app/views/shared/_footer.html.erb
<footer>
	<hr />
	<p>
		
		<span style="display:inline-block; vertical-align:middle">
		<%= link_to image_tag("facebook_32.png"), "http://www.facebook.com/100000080021994", :target => "_blank" %>
		<%= link_to image_tag("linkedin_32.png"), "http://www.linkedin.com/pub/jeff-barriault/46/7/97", :target => "_blank" %>
		<%= link_to image_tag("twitter_32.png"), "https://twitter.com/JeffBarriault", :target => "_blank" %>
		<%= link_to image_tag("github_32.png"), "https://github.com/barriault", :target => "_blank" %>
		</span>
		&copy; 2012 - Jeff Barriault
	</p>
</footer>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
			<%= link_to "Jeff Barriault", root_path, :class => "brand" %>
			<ul class="nav">
				<% if current_page?(root_path) %><li class="active"><% else %><li><% end %><%= link_to "Home", root_path %></li>
				<li><%= link_to "Photography", photography_path %></li>
				<% if current_page?(posts_path) %><li class="active"><% else %><li><% end %><%= link_to "Blog", posts_path %></li>
				<% if current_page?(programming_path) %><li class="active"><% else %><li><% end %><%= link_to "Programming", programming_path %></li>
				<% if current_page?(about_path) %><li class="active"><% else %><li><% end %><%= link_to "About", about_path %></li>
				<% if current_page?(contact_path) %><li class="active"><% else %><li><% end %><%= link_to "Contact", contact_path %></li>
			</ul>
			<p class="navbar-text pull-right">
			<% if user_signed_in? -%>
				<%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
			<% else -%>
				<%= link_to('Sign In', new_user_session_path)  %>
			<% end -%>
			</p>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="hero-unit" style="padding-left: 70px;">

	<div id='slideshowHolder'>
		<%= image_tag("http://photography.barriault.net/photos/i-L6N3GND/0/L/i-L6N3GND-L.jpg") %>
		<%= image_tag("http://photography.barriault.net/photos/i-fjQPcjC/2/L/i-fjQPcjC-L.jpg") %>
		<%= image_tag("http://photography.barriault.net/photos/i-QmR2v64/0/L/i-QmR2v64-L.jpg") %>
		<%= image_tag("http://photography.barriault.net/photos/i-FFKZMRg/2/L/i-FFKZMRg-L.jpg") %>
		<%= image_tag("http://photography.barriault.net/photos/i-kcjNpVF/0/L/i-kcjNpVF-L.jpg") %>
		<%= image_tag("http://photography.barriault.net/photos/i-3MWrrK6/2/L/i-3MWrrK6-L.jpg") %>
		<%= image_tag("http://photography.barriault.net/photos/i-2HPFmqX/0/L/i-2HPFmqX-L.jpg") %>
		<%= image_tag("http://photography.barriault.net/photos/i-7K9kdt6/2/L/i-7K9kdt6-L.jpg") %>
	</div>

</div>

<div class="row">

	<div class="span2">
		<%= link_to image_tag("http://www.adorama.com/artworks2/banners/affil/adorama_2011_125x125.jpg", :class => "thumbnail"), "http://www.adorama.com/?kbid=67100", :target => "_blank" %>
	</div>

	<div class="span2">
		<div class="thumbnail">
			<iframe src="http://rcm.amazon.com/e/cm?t=jeffbarr-20&o=1&p=21&l=ur1&category=electronics&f=ifr" width="125" height="125" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
		</div>
	</div>

	<div class="span2">
		<%= link_to image_tag("smug_mug_logo.png", :class => "thumbnail"), "https://secure.smugmug.com/signup.mg?Coupon=JeGhWNBh5bGbA", :target => "_blank" %>	</div>

	<div class="span2">
		<%= link_to image_tag("logo_independentdistributor2010_verticle.jpg", :class => "thumbnail nsslogo", :style => "height: 125px;"), "http://www.naturessunshine.com/?actid=2881095", :target => "_blank" %>
	</div>

	<div class="span2">
		<div class="thumbnail">
		<script type="text/javascript"><!--
		google_ad_client = "ca-pub-3870257494761218";
		/* barriault.net homepage */
		google_ad_slot = "3791304980";
		google_ad_width = 125;
		google_ad_height = 125;
		//-->
		</script>
		<script type="text/javascript"
		src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
		</script>
		</div>
	</div>

	<div class="span2">
		<%= link_to image_tag("http://www.adorama.com/artworks2/banners/affil/AdoramaPix_2010_125_125.gif", :class => "thumbnail"), "http://www.adorama.com/catalog.tpl?op=gotopix&sterm=lab&kbid=67100", :target => "_blank" %>
	</div>

</div>